services:
  bilbob-data:
    image: bilbob-data
    build:
      context: backend
      dockerfile: data.Dockerfile
    environment:
      POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
  bilbob-api:
    image: bilbob-api
    build:
      context: backend
      dockerfile: api.Dockerfile
    ports:
      - ${IP_ADDR}:${API_PORT}:8080
    environment:
      - DB_HOST=bilbob-data
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=postgres
      - GIN_MODE=release
      - HOSTNAME=${HOSTNAME}
      - PROTOCOL=${PROTOCOL}
      - LP_PORT=${EXPOSED_PORT}
      - WEBAPP_PORT=${EXPOSED_PORT}
    volumes:
      - assets:/assets
  bilbob-staticserver:
    image: bilbob-staticserver
    build: .
    ports:
      - ${IP_ADDR}:${EXPOSED_PORT}:8080
    environment:
      - DB_HOST=data
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=postgres
      - HOSTNAME=${HOSTNAME}
      - PROTOCOL=${PROTOCOL}
      - API_PORT=${API_PORT}
      - LP_PATH=${LP_PATH}
      - LP_PORT=${EXPOSED_PORT}
      - WEBAPP_PORT=${EXPOSED_PORT}
      - LP_MODE=release
volumes:
  pgdata:
  assets:
