services:
  data:
    image: bilbob-data
    build:
      context: backend
      dockerfile: data.Dockerfile
    environment:
      POSTGRES_PASSWORD=secret
  api:
    image: bilbob-api
    build:
      context: backend
      dockerfile: api.Dockerfile
    ports:
      - ${IP_ADDR}:${REACT_APP_API_PORT}:8080
    environment:
      - DB_HOST=data
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=postgres
      - HOSTNAME=${REACT_APP_HOSTNAME}
      - PROTOCOL=${REACT_APP_PROTOCOL}
      - LANDING_PAGE_PORT=${REACT_APP_LANDING_PAGE_PORT}
      - WEBAPP_PORT=${REACT_APP_WEBAPP_PORT}
    stop_grace_period: 1s
  landing-page:
    image: bilbob-landing-page
    build:
      context: landing-page
      dockerfile: web-server.Dockerfile
    ports:
      - ${IP_ADDR}:${REACT_APP_LANDING_PAGE_PORT}:8080
    environment:
      - HOSTNAME=${REACT_APP_HOSTNAME}
      - PROTOCOL=${REACT_APP_PROTOCOL}
      - API_PORT=${REACT_APP_API_PORT}
      - WEBAPP_PORT=${REACT_APP_WEBAPP_PORT}
    volumes:
      - ./landing-page/resources:/go/bin/resources
    stop_grace_period: 1s
  webapp:
    image: bilbob-webapp
    build:
      context: webapp
      dockerfile: node.Dockerfile
    ports:
      - ${IP_ADDR}:${REACT_APP_WEBAPP_PORT}:3000
    volumes:
      - ./webapp:/webapp
      - .env:/webapp/.env
    stop_grace_period: 1s
