services:
  data:
    image: bilbob-data
    build:
      context: backend
      dockerfile: data.Dockerfile
    environment:
      POSTGRES_PASSWORD=secret
  api:
    image: bilbob-api
    build:
      context: backend
      dockerfile: api.Dockerfile
    ports:
      - 127.0.0.1:8081:8080
    environment:
      - DB_HOST=data
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=postgres
    working_dir: /go/bin
    command: sh -c "sleep 3 && ./api"
    stop_grace_period: 1s
  landing-page:
    image: bilbob-landing-page
    build:
      context: landing-page
      dockerfile: web-server.Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./landing-page/resources:/go/bin/resources
    working_dir: /go/bin
    command: sh -c "sleep 4 && ./web-server"
    stop_grace_period: 1s
