services:
  data:
    image: bilbob-data
    build:
      context: backend
      dockerfile: data.Dockerfile
    environment:
      POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    image: bilbob-api
    build:
      context: backend
      dockerfile: api.Dockerfile
    ports:
      - ${IP_ADDR}:${REACT_APP_API_PORT}:8080
    volumes:
      - assets:/assets
    environment:
      - DB_HOST=data
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=postgres
      - HOSTNAME=${REACT_APP_HOSTNAME}
      - PROTOCOL=${REACT_APP_PROTOCOL}
      - LANDING_PAGE_PORT=${REACT_APP_LANDING_PAGE_PORT}
      - WEBAPP_PORT=${REACT_APP_WEBAPP_PORT}
      - GIN_MODE=release
  landing-page:
    image: bilbob-landing-page
    build:
      context: landing-page
      dockerfile: web-server.Dockerfile
    ports:
      - ${IP_ADDR}:${REACT_APP_LANDING_PAGE_PORT}:8080
    environment:
      - HOSTNAME=${REACT_APP_HOSTNAME}
      - PROTOCOL=${REACT_APP_PROTOCOL}
      - API_PORT=${REACT_APP_API_PORT}
      - WEBAPP_PORT=${REACT_APP_WEBAPP_PORT}
    volumes:
      - ./landing-page/resources:/go/bin/resources
  webapp:
    image: bilbob-webapp-prod
    build:
      context: .
      dockerfile: webapp/prod.Dockerfile
    ports:
      - ${IP_ADDR}:${REACT_APP_WEBAPP_PORT}:3000

volumes:
  pgdata:
  assets:
