services:
  data:
    image: bilbob-data
    build:
      context: .
      dockerfile: data.Dockerfile
    environment:
      POSTGRES_PASSWORD=secret
  api:
    image: bilbob-api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 127.0.0.1:8080:8080
    working_dir: /go/bin
    command: sh -c "sleep 3 && ./api"
